### PR TITLE
Library for evaluating DR Events

### PR DESCRIPTION
**Pull request by jleyden**

### CODE REVIEW

**Comment by jleyden** [comment]
1. Removed `.DS_Store`
2. We need the pricing library to calculate the costs of the actual and predicted energy consumption. Let me know if there is a cleaner way to use this library.
3. Added examples

**Comment by jleyden** [comment]
@gtfierro this is the new PR. Answers to your questions above.

**Comment by gtfierro** [comment]
Has the pricing library been put on PyPi at all? If it hasn't, then we may want to reach out to Olivier to see if he's willing to do that

Your examples look great. Is there a way to use the library to get a prediction for a point in the future?

**Comment by jleyden** [comment]
1. Just asked him.

2. No, the predictions are meant for evaluating a DR event that already occurred.
We are predicting is a "baseline" energy consumption: What energy consumption would have been if we did not change energy consumption due to DR event pricing.
With the "baseline", we can compute savings = baseline consumption - actual consumption.

**Comment by gtfierro** [comment]
Ok, we'll hear back from him soon. We might need to include the pricing package as a git submodule rather than copied files so that it can be updated.

**Comment by jleyden** [comment]
@gtfierro using electricitycostcalculator now

**Comment by gtfierro** [comment]
Nice work!

**Pull request merged**
